version: '3.6'

services:

  db:
    image: postgres:alpine
    container_name: bb-postgres
    restart: "no"
    volumes:
      - ./docker/var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: jesus
      POSTGRES_PASSWORD: christ
      POSTGRES_DB: BreakingBread
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 10260:5432

  adminer:
    image: adminer:latest
    container_name: bb-adminer
    links:
      - db
    restart: always
    ports:
      - 10261:8080
